Repository githubschool/open-enrollment-classes-introduction-to-github, pull requests merged in 2018-09, with the labels that each got.

#20565 Adding Geekgurus coordinants
  _pins/Geekgurus.json
Labels: Fixed

#20825 sophgoes pins Taiwan
  _pins/sophgoes.json
Labels: Assigned, TEST - Learning Git

#20914 Add ndungur's City Address
  _pins/ndungur.json
Labels: Githubteacher was here, TEST - Learning Git
